spring.application.name=island-recipes-app
server.port=${PORT:8080}
spring.data.mongodb.uri=mongodb+srv://beppers87:${DB_PASSWORD}@dev-island-recipes.ibx5f.mongodb.net/Project0?retryWrites=true&w=majority&appName=dev-island-recipes
allowed.origins=${ALLOWED_ORIGINS:*}
